enabled: false
world: "zaworld"
spawn_x: 0
spawn_y: 60
spawn_z: 0
spawn_yaw: 0
spawn_pitch: 0
spawn_giant: true
giant_x: 0
giant_y: 60
giant_z: 0
giant_yaw: 0
giant_pitch: 0
arena_pos1_x: 0
arena_pos1_z: 0
arena_pos2_x: 0
arena_pos2_z: 0
zombies_spawn_countdown: 10
message_prefix: "[ZA]"
message_phase_night: "It's night of phase %phase%. Remaining until the end: %countdown%"
message_phase_day: "It's day after phase %phase%. Remaining until the end: %countdown%"
message_have_points: "You have %points% points."
message_join: "%name% is join to game."
message_leave: "%name% is leave the game."
message_gift_got: "You got your Daily gift: %gift%"
message_gift_already_have: "You already have Daily gift. Try it tomorrow."
message_change_player: "%name% is changed to player."
message_change_spectator: "%name% is changed to spectator."
message_giant_spawned: "Giant spawned. Apocalypse will end after kill giant."
message_giant_killed: "Giant killed. Apocalypse is restarting now."
message_phase_start: "Zombie apocalypse started. Phase: %number%"
message_death_player: "%player% killed by %killer%."
message_player_get_points: "You killed %entity% and got %points% points. Your points: %newpoints% "
message_player_miss_points: "You killed by %killer% and miss %points% points. Your points: %newpoints% "
message_starting: "Zombie Apocalypse starting in %time%"
message_minutes: "minutes"
message_minute: "minute"
message_seconds: "seconds"
message_second: "second"
message_arena_teleport: "You are teleported to arena."
message_arena_already_in: "You are already in arena."
message_players_in_arena: "In arena is %count% players."
help_spectate: "Change from player to spectator and from spectator to player."
help_list: "List of players in Arena"
help_join: "Join to Arena"
help_points: "Display your points"
help_gift: "Get daily gift to you"
help_phaseinfo: "Display actual phase, countdown to end of phase and day after phase"
help_setspawnloc: "Admin Command: set spawn location"
help_setgiantloc: "Admin Command: set giant location"
help_setpos1: "Admin Command: set arena pos 1"
help_setpos2: "Admin Command: set arena pos 2"
help_enablegame: "Admin Command: enable/disable game"
help_enablegiantgame: "Admin Command: enable/disable spawning giants"